### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Ph-St** [rschroll/rmrl#19]
For some files, I get this error:

Traceback (most recent call last):
  File "/home/xxx/Downloads/rmirro-main/render_rmrl.py", line 31, in <module>
    status = render_rmrl(infile, outfile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/Downloads/rmirro-main/render_rmrl.py", line 18, in render_rmrl
    stream = render(input)
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rmrl/render.py", line 157, in render
    if apply_ocg:
       ^^^^^^^^^
UnboundLocalError: cannot access local variable 'apply_ocg' where it is not associated with a value.

apply_ocg is set a few lines above, however inside a for-loop. So I assume there's nothing to loop through at this point and hence the variable is not being set. Setting it just before line 157 removed the error, but the resulting file is broken, so something more is going on...

**Comment by simonsebold** [comment]
Can reproduce. Including broken PDF when setting the variable manually.
If you export an annotated PDF it doesn't crash but exports just the PDF without the annotations.

**Comment by monstrencage** [comment]
I have experienced the same issue.
